apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-stack-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SymulKabir/GitOps-infra.git
    path: apps/full-stack-app
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
